[package]
name = "annotation-rs"
version = "0.1.0"
authors = ["dark-flames <dark_flames@outlook.com>"]
license = "MIT OR Apache-2.0"
description = "An attribute reader generator for Rust"
repository = "https://github.com/dark-flames/Yui"
keywords = ["yui", "attribute-reader"]
include = ["src/*.rs", "crates-io.md", "LICENSE-APACHE", "LICENSE-MIT"]
readme = "crates-io.md"
edition = "2018"

[dependencies]
derive = { path = "./derive" }
helpers = { path = "./helpers" }
syn = "1.0"

[dev-dependencies]
test-object = { path = "./test_object" }
test-macro = { path = "./test_macro" }
float-cmp = "0.8.0"


[features]
generate-reader=[]

[workspace]
members = [
    "derive",
    "helpers",
    "test_object",
    "test_macro"
]
